---
title: Karine FREYMANN
timezone: UTC
collections:
  expos:
    title: Expos
    output: true
  portraits:
    title: Portraits
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
kramdown:
  input: GFM
  hard_wrap: false
gems:
- jekyll-coffeescript
- jekyll-paginate
email: ''
description: Portfolio
url: http://www.karinefreymann.fr
baseurl: "/karinefreymann.github.io"
facebook_username: Karine-Freymann-artiste-peintre-115872508495409
twitter_username: ''
instagram_username: ''
github_username: ''
deviantart_username: ''
flickr_username: ''
discus_shortname: ''
share: true
comments:
  provider: disqus
  disqus:
    short_name: ''
nav:
- EXPOS: "/expos/"
- PORTRAITS: "/portraits/"
- JOURNAL: "/journal/"
defaults:
  -
    scope:
      path: ""
      type: "portraits"
    values:
      title: ""
      technique: ["Acrylique sur toile","Dessin Ã  l'encre de chine"]
      dimensions:
      photo:
translations:
  permalink: "/404.html"
destination: "./_site"
port: 4000
markdown: kramdown
highlighter: rouge
permalink: "/journal/:title/"
paginate: 5
paginate_path: "/journal/page:num/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
sitemap:
  file: "/sitemap.xml"
  exclude:
  - "/atom.xml"
  - "/feed.xml"
  - "/feed/index.xml"
  include_posts:
  - "/writing/"
  change_frequency_name: change_frequency
  priority_name: priority
